// js/banners-catalog.js
// The Alliance Banner catalog: the 19 known banners tracked across seasons.

export const BANNERS = Object.freeze([
  Object.freeze({
    id: 'sarafina',
    name: 'Sarafina',
    group: '1097',
    availability: '1-3 / 14-19',
    points: 'Full',
    pilot: 'Sarafino',
    status: 'Perm',
  }),
  Object.freeze({
    id: 'angel-banner',
    name: 'Angel Banner',
    group: '1097',
    availability: '0-5 / 10',
    points: 'Full',
    pilot: 'Angel/Kiji',
    status: 'Perm',
  }),
  Object.freeze({
    id: 'undead',
    name: 'Undead',
    group: '1097',
    availability: '',
    points: 'Full',
    pilot: 'Undead',
    status: 'Perm',
  }),
  Object.freeze({
    id: 'amira-zee',
    name: 'Amira Zee',
    group: '1097',
    availability: '',
    points: 'Full',
    pilot: 'Zena',
    status: 'Perm',
  }),
  Object.freeze({
    id: 'zena-banner',
    name: 'Zena Banner',
    group: '1097',
    availability: '',
    points: 'Full',
    pilot: 'Zena',
    status: 'Half Season',
  }),
  Object.freeze({
    id: 'redbull-banner',
    name: 'Redbull Banner',
    group: '1097',
    availability: '',
    points: 'Full',
    pilot: 'Redbull',
    status: 'Perm',
  }),
  Object.freeze({
    id: 'viper',
    name: 'Viper',
    group: '1097',
    availability: '',
    points: 'Full',
    pilot: 'Redbull',
    status: 'Perm',
  }),
  Object.freeze({
    id: 'teresita-02',
    name: 'Teresita (02)',
    group: '1097',
    availability: '',
    points: 'Full',
    pilot: 'Redbull',
    status: 'Perm',
  }),
  Object.freeze({
    id: 'oso',
    name: 'OSO',
    group: '1097',
    availability: '',
    points: 'Full',
    pilot: 'Redbull',
    status: 'Perm',
  }),
  Object.freeze({
    id: 'kika',
    name: 'Kika',
    group: '1097',
    availability: '5-20',
    points: 'Full',
    pilot: 'Kika',
    status: 'Perm',
  }),
  Object.freeze({
    id: 'roha-banner',
    name: 'Roha Banner',
    group: '1097',
    availability: '',
    points: '',
    pilot: 'Roha',
    status: 'Perm',
  }),
  Object.freeze({
    id: 'ak-banner',
    name: 'AK Banner',
    group: '1097',
    availability: '',
    points: '',
    pilot: '',
    status: 'Find info',
  }),
  Object.freeze({
    id: 'maximus-banner',
    name: 'Maximus Banner',
    group: '1097',
    availability: '',
    points: '',
    pilot: '',
    status: 'Find info',
  }),
  Object.freeze({
    id: 'big-boiie',
    name: 'BiG BOiiE',
    group: '1097',
    availability: '',
    points: '',
    pilot: '',
    status: 'Find info',
  }),
  Object.freeze({
    id: 'kika-banner-2',
    name: 'Kika Banner 2',
    group: '1100',
    availability: '5-20',
    points: 'Full',
    pilot: 'Kika',
    status: 'Perm',
  }),
  Object.freeze({
    id: 'beatz',
    name: 'Beatz',
    group: '1100',
    availability: '5-20',
    points: '59 points',
    pilot: 'Kika',
    status: 'WIP',
  }),
  Object.freeze({
    id: 'alex-kika',
    name: 'Alex&Kika',
    group: '1100',
    availability: '5-20',
    points: '55 points',
    pilot: 'Kika',
    status: 'WIP',
  }),
  Object.freeze({
    id: 'footloos-banner',
    name: 'Footloos Banner',
    group: 'Others',
    availability: '',
    points: '',
    pilot: '',
    status: 'Find Info',
  }),
  Object.freeze({
    id: 'molly-banner',
    name: 'Molly Banner',
    group: 'Others',
    availability: '',
    points: '',
    pilot: '',
    status: 'Find Info',
  }),
]);

export const BANNER_IDS = Object.freeze(BANNERS.map((banner) => banner.id));
