import { formatLocaleDate } from '../locale-format.js';

const REQUIRED_KEYS = Object.freeze([
  'export.team',
  'export.state',
  'export.score',
  'export.generatedBy',
  'loyalty.unit.hour.short',
  'loyalty.unit.hour.long',
  'loyalty.unit.minute.short',
  'loyalty.unit.minute.long',
  'loyalty.unit.second.short',
  'loyalty.unit.second.long',
]);

const COPY = Object.freeze({
  en: Object.freeze({
    'export.team': 'TEAM',
    'export.state': 'STATE',
    'export.score': 'SCORE',
    'export.generatedBy': 'Generated by',
    'loyalty.unit.hour.short': 'h',
    'loyalty.unit.hour.long': 'Hours',
    'loyalty.unit.minute.short': 'm',
    'loyalty.unit.minute.long': 'Minutes',
    'loyalty.unit.second.short': 's',
    'loyalty.unit.second.long': 'Seconds',
  }),
  es: Object.freeze({
    'export.team': 'EQUIPO',
    'export.state': 'ESTADO',
    'export.score': 'PUNTUACIÓN',
    'export.generatedBy': 'Creado con',
    'loyalty.unit.hour.short': 'h',
    'loyalty.unit.hour.long': 'Horas',
    'loyalty.unit.minute.short': 'min',
    'loyalty.unit.minute.long': 'Minutos',
    'loyalty.unit.second.short': 's',
    'loyalty.unit.second.long': 'Segundos',
  }),
  pt: Object.freeze({
    'export.team': 'EQUIPE',
    'export.state': 'ESTADO',
    'export.score': 'PONTUAÇÃO',
    'export.generatedBy': 'Criado com',
    'loyalty.unit.hour.short': 'h',
    'loyalty.unit.hour.long': 'Horas',
    'loyalty.unit.minute.short': 'min',
    'loyalty.unit.minute.long': 'Minutos',
    'loyalty.unit.second.short': 's',
    'loyalty.unit.second.long': 'Segundos',
  }),
  de: Object.freeze({
    'export.team': 'TEAM',
    'export.state': 'STAAT',
    'export.score': 'PUNKTZAHL',
    'export.generatedBy': 'Erstellt mit',
    'loyalty.unit.hour.short': 'Std.',
    'loyalty.unit.hour.long': 'Stunden',
    'loyalty.unit.minute.short': 'Min.',
    'loyalty.unit.minute.long': 'Minuten',
    'loyalty.unit.second.short': 'Sek.',
    'loyalty.unit.second.long': 'Sekunden',
  }),
  fr: Object.freeze({
    'export.team': 'ÉQUIPE',
    'export.state': 'ÉTAT',
    'export.score': 'SCORE',
    'export.generatedBy': 'Créé avec',
    'loyalty.unit.hour.short': 'h',
    'loyalty.unit.hour.long': 'Heures',
    'loyalty.unit.minute.short': 'min',
    'loyalty.unit.minute.long': 'Minutes',
    'loyalty.unit.second.short': 's',
    'loyalty.unit.second.long': 'Secondes',
  }),
  tr: Object.freeze({
    'export.team': 'TAKIM',
    'export.state': 'EYALET',
    'export.score': 'PUAN',
    'export.generatedBy': 'Oluşturan:',
    'loyalty.unit.hour.short': 'sa',
    'loyalty.unit.hour.long': 'Saat',
    'loyalty.unit.minute.short': 'dk',
    'loyalty.unit.minute.long': 'Dakika',
    'loyalty.unit.second.short': 'sn',
    'loyalty.unit.second.long': 'Saniye',
  }),
  ru: Object.freeze({
    'export.team': 'КОМАНДА',
    'export.state': 'ШТАТ',
    'export.score': 'СЧЁТ',
    'export.generatedBy': 'Создано в',
    'loyalty.unit.hour.short': 'ч',
    'loyalty.unit.hour.long': 'Часы',
    'loyalty.unit.minute.short': 'мин',
    'loyalty.unit.minute.long': 'Минуты',
    'loyalty.unit.second.short': 'с',
    'loyalty.unit.second.long': 'Секунды',
  }),
  id: Object.freeze({
    'export.team': 'TIM',
    'export.state': 'NEGARA BAGIAN',
    'export.score': 'SKOR',
    'export.generatedBy': 'Dibuat dengan',
    'loyalty.unit.hour.short': 'jam',
    'loyalty.unit.hour.long': 'Jam',
    'loyalty.unit.minute.short': 'mnt',
    'loyalty.unit.minute.long': 'Menit',
    'loyalty.unit.second.short': 'dtk',
    'loyalty.unit.second.long': 'Detik',
  }),
  it: Object.freeze({
    'export.team': 'TEAM',
    'export.state': 'STATO',
    'export.score': 'PUNTEGGIO',
    'export.generatedBy': 'Generato da',
    'loyalty.unit.hour.short': 'h',
    'loyalty.unit.hour.long': 'Ore',
    'loyalty.unit.minute.short': 'min',
    'loyalty.unit.minute.long': 'Minuti',
    'loyalty.unit.second.short': 's',
    'loyalty.unit.second.long': 'Secondi',
  }),
  zh: Object.freeze({
    'export.team': '战队',
    'export.state': '州',
    'export.score': '得分',
    'export.generatedBy': '生成自',
    'loyalty.unit.hour.short': '时',
    'loyalty.unit.hour.long': '小时',
    'loyalty.unit.minute.short': '分',
    'loyalty.unit.minute.long': '分钟',
    'loyalty.unit.second.short': '秒',
    'loyalty.unit.second.long': '秒',
  }),
  ar: Object.freeze({
    'export.team': 'الفريق',
    'export.state': 'الولاية',
    'export.score': 'النقاط',
    'export.generatedBy': 'تم الإنشاء بواسطة',
    'loyalty.unit.hour.short': 'س',
    'loyalty.unit.hour.long': 'الساعات',
    'loyalty.unit.minute.short': 'د',
    'loyalty.unit.minute.long': 'الدقائق',
    'loyalty.unit.second.short': 'ث',
    'loyalty.unit.second.long': 'الثواني',
  }),
  kr: Object.freeze({
    'export.team': '팀',
    'export.state': '주',
    'export.score': '점수',
    'export.generatedBy': '제작:',
    'loyalty.unit.hour.short': '시간',
    'loyalty.unit.hour.long': '시간',
    'loyalty.unit.minute.short': '분',
    'loyalty.unit.minute.long': '분',
    'loyalty.unit.second.short': '초',
    'loyalty.unit.second.long': '초',
  }),
});

function normalizeLocale(locale) {
  const primary = String(locale || 'en')
    .trim()
    .toLowerCase()
    .split('-')[0];
  const normalized = primary === 'ko' ? 'kr' : primary;
  return Object.hasOwn(COPY, normalized) ? normalized : 'en';
}

export function outputCopyText(locale, key) {
  const normalized = normalizeLocale(locale);
  return COPY[normalized]?.[key] || COPY.en[key] || key;
}

export function buildComboExportCopy(locale, date = new Date()) {
  return Object.freeze({
    teamStateLine: `${outputCopyText(locale, 'export.team')} VTS — ${outputCopyText(locale, 'export.state')} 1097  •  Rise of Castles: Ice & Fire`,
    scoreLabel: outputCopyText(locale, 'export.score'),
    generatedByLine: `${outputCopyText(locale, 'export.generatedBy')} VTS 1097 Hero Combo Creator  •  Rise of Castles: Ice & Fire`,
    dateLabel: formatLocaleDate(date, locale, {
      month: 'long',
      day: 'numeric',
      year: 'numeric',
    }),
  });
}

export function auditOutputCopy() {
  const missing = [];
  const empty = [];
  const unexpected = [];

  for (const [locale, localeCopy] of Object.entries(COPY)) {
    for (const key of REQUIRED_KEYS) {
      if (!Object.hasOwn(localeCopy, key)) missing.push(`${locale}:${key}`);
      else if (!String(localeCopy[key]).trim()) empty.push(`${locale}:${key}`);
    }
    for (const key of Object.keys(localeCopy)) {
      if (!REQUIRED_KEYS.includes(key)) unexpected.push(`${locale}:${key}`);
    }
  }

  return Object.freeze({
    complete: missing.length === 0 && empty.length === 0 && unexpected.length === 0,
    missing: Object.freeze(missing),
    empty: Object.freeze(empty),
    unexpected: Object.freeze(unexpected),
  });
}

export const OUTPUT_COPY_LOCALES = Object.freeze(Object.keys(COPY));
export const OUTPUT_COPY_KEYS = REQUIRED_KEYS;
