import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

import {
  OUTPUT_COPY_KEYS,
  OUTPUT_COPY_LOCALES,
  auditOutputCopy,
  buildComboExportCopy,
  outputCopyText,
} from '../../js/i18n/output-copy.js';
import {
  formatLocaleNumber,
  resolveIntlLocale,
  resolveRuntimeLocale,
} from '../../js/locale-format.js';

const SUPPORTED_LOCALES = Object.freeze([
  'en',
  'es',
  'pt',
  'de',
  'fr',
  'tr',
  'ru',
  'id',
  'zh',
  'ar',
  'kr',
  'it',
]);

test('export and loyalty output copy covers every stable ID in all 12 locales', () => {
  assert.deepEqual([...OUTPUT_COPY_LOCALES].sort(), [...SUPPORTED_LOCALES].sort());
  assert.deepEqual(OUTPUT_COPY_KEYS, [
    'export.team',
    'export.state',
    'export.score',
    'export.generatedBy',
    'loyalty.unit.hour.short',
    'loyalty.unit.hour.long',
    'loyalty.unit.minute.short',
    'loyalty.unit.minute.long',
    'loyalty.unit.second.short',
    'loyalty.unit.second.long',
  ]);

  const audit = auditOutputCopy();
  assert.equal(audit.complete, true);
  assert.deepEqual(audit.missing, []);
  assert.deepEqual(audit.empty, []);
  assert.deepEqual(audit.unexpected, []);

  for (const locale of SUPPORTED_LOCALES) {
    for (const key of OUTPUT_COPY_KEYS) {
      assert.notEqual(outputCopyText(locale, key), key, `${locale}:${key}`);
    }
  }
  assert.equal(outputCopyText('ko-KR', 'export.score'), outputCopyText('kr', 'export.score'));
});

test('combo export copy uses the selected locale for labels and the calendar date', () => {
  const date = new Date(Date.UTC(2026, 6, 16, 12));
  const german = buildComboExportCopy('de', date);
  const arabic = buildComboExportCopy('ar', date);

  assert.match(german.teamStateLine, /^TEAM VTS — STAAT 1097/);
  assert.equal(german.scoreLabel, 'PUNKTZAHL');
  assert.match(german.generatedByLine, /^Erstellt mit VTS 1097/);
  assert.equal(
    german.dateLabel,
    new Intl.DateTimeFormat(resolveIntlLocale('de'), {
      month: 'long',
      day: 'numeric',
      year: 'numeric',
    }).format(date)
  );
  assert.notEqual(german.dateLabel, buildComboExportCopy('en', date).dateLabel);
  assert.match(arabic.teamStateLine, /الفريق VTS — الولاية 1097/);
});

test('runtime locale resolution follows stored, prepaint, and document language hints', () => {
  const previousDocument = globalThis.document;
  const previousStorage = globalThis.localStorage;
  const previousInitialLanguage = globalThis.VTS_INITIAL_LANGUAGE;
  let stored = '';
  try {
    globalThis.localStorage = { getItem: () => stored };
    globalThis.VTS_INITIAL_LANGUAGE = '';
    globalThis.document = { documentElement: { lang: 'fr-FR' } };
    assert.equal(resolveRuntimeLocale(), 'fr');
    globalThis.document.documentElement.lang = 'ko-KR';
    assert.equal(resolveRuntimeLocale(), 'kr');
    stored = 'tr';
    assert.equal(resolveRuntimeLocale(), 'tr');
  } finally {
    if (previousDocument === undefined) delete globalThis.document;
    else globalThis.document = previousDocument;
    if (previousStorage === undefined) delete globalThis.localStorage;
    else globalThis.localStorage = previousStorage;
    if (previousInitialLanguage === undefined) delete globalThis.VTS_INITIAL_LANGUAGE;
    else globalThis.VTS_INITIAL_LANGUAGE = previousInitialLanguage;
  }
});

test('canvas, Arcade, and loyalty views consume locale-aware presentation helpers', async () => {
  const [appSource, exportSource, arcadeSource, loyaltySource, loyaltyTemplate] = await Promise.all(
    [
      readFile(new URL('../../js/app.js', import.meta.url), 'utf8'),
      readFile(new URL('../../js/app-export.js', import.meta.url), 'utf8'),
      readFile(new URL('../../js/arcade-lobby-ui.js', import.meta.url), 'utf8'),
      readFile(new URL('../../js/loyalty-calculator.js', import.meta.url), 'utf8'),
      readFile(new URL('../../tabs/loyalty.html', import.meta.url), 'utf8'),
    ]
  );

  assert.match(exportSource, /buildComboExportCopy\(currentLanguage\)/);
  assert.match(exportSource, /fillText\(exportCopy\.teamStateLine/);
  assert.match(exportSource, /fillText\(exportCopy\.scoreLabel/);
  assert.match(exportSource, /fillText\(exportCopy\.generatedByLine/);
  assert.match(exportSource, /fillText\(exportCopy\.dateLabel/);
  assert.doesNotMatch(exportSource, /toLocaleDateString\('en-US'/);
  assert.doesNotMatch(exportSource, /fillText\('(?:TEAM VTS|SCORE|Generated by)/);
  assert.match(exportSource, /const S\s+= 2/);
  assert.match(exportSource, /const W\s+= 820/);
  assert.match(exportSource, /canvas\.width\s+= W \* S/);

  assert.match(appSource, /t\.generatorScoreLabel \|\| 'Score:'/);
  assert.match(appSource, /formatLocaleNumber\(info\.score, currentLanguage/);
  assert.match(appSource, /formatLocaleNumber\(info\.rank, currentLanguage\)/);
  assert.doesNotMatch(appSource, /` \(Score: \$\{info\.score\}, #\$\{info\.rank\}\)`/);

  assert.match(arcadeSource, /formatLocaleNumber\(value, currentLang\(\)\)/);
  assert.match(arcadeSource, /formatArcadeNumber\(row\.score\)/);
  assert.match(arcadeSource, /formatArcadeNumber\(row\.rating\)/);
  assert.match(arcadeSource, /formatArcadeNumber\(best\)/);
  assert.doesNotMatch(arcadeSource, /\.toLocaleString\(\)/);
  assert.equal(formatLocaleNumber(1234567, 'de'), '1.234.567');
  assert.equal(formatLocaleNumber(1234567, 'en'), '1,234,567');

  for (const unit of ['hour', 'minute', 'second']) {
    assert.match(
      loyaltyTemplate,
      new RegExp(`data-output-copy="loyalty\\.unit\\.${unit}\\.short"`)
    );
    assert.match(
      loyaltyTemplate,
      new RegExp(`data-output-copy-aria="loyalty\\.unit\\.${unit}\\.long"`)
    );
  }
  assert.match(loyaltySource, /function localizeLoyaltyTimeUnits\(\)/);
  assert.match(
    loyaltySource,
    /window\.addEventListener\('edenLanguageUpdate',[\s\S]*localizeLoyaltyTimeUnits\(\)/
  );
});
